version: '2'
services:
  db: 
    build: db
    expose:
     - 27017
    command: "--smallfiles"
    networks:
      - backbone
  api:
    build: api
    ports:
     - 4200
    networks:
     - backbone
  ui:
    build: ui
    ports:
     - 3000:3000
    networks:
     - backbone
networks:
  backbone:
    external: true
