version: '2'
services:
  db: 
    build: db
    ports:
     - "27017:27017"
    command: "--smallfiles"
  api:
    build: api
    ports:
     - "4200:4200"
  # ui:
  #   build: ui
  #   ports:
  #    - "3000:3000"

